<?php

use yii\db\Migration;

class m180910_010959_sys_action_log extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%sys_action_log}}', [
            'id' => 'int(10) NOT NULL AUTO_INCREMENT COMMENT \'主键\'',
            'manager_id' => 'int(10) NOT NULL DEFAULT \'0\' COMMENT \'执行用户id\'',
            'behavior' => 'varchar(50) NULL DEFAULT \'\' COMMENT \'行为类别\'',
            'method' => 'varchar(20) NULL DEFAULT \'\' COMMENT \'提交类型\'',
            'module' => 'varchar(50) NULL DEFAULT \'\' COMMENT \'模块\'',
            'controller' => 'varchar(50) NULL DEFAULT \'\' COMMENT \'控制器\'',
            'action' => 'varchar(50) NULL DEFAULT \'\' COMMENT \'控制器方法\'',
            'url' => 'varchar(1000) NULL DEFAULT \'\' COMMENT \'提交url\'',
            'get_data' => 'text NULL COMMENT \'get数据\'',
            'post_data' => 'longtext NULL COMMENT \'post数据\'',
            'ip' => 'varchar(16) NULL DEFAULT \'\' COMMENT \'ip地址\'',
            'remark' => 'varchar(255) NULL DEFAULT \'\' COMMENT \'日志备注\'',
            'country' => 'varchar(50) NULL DEFAULT \'\' COMMENT \'国家\'',
            'provinces' => 'varchar(50) NULL DEFAULT \'\' COMMENT \'省\'',
            'city' => 'varchar(50) NULL DEFAULT \'\' COMMENT \'城市\'',
            'status' => 'tinyint(4) NOT NULL DEFAULT \'1\' COMMENT \'状态[-1:删除;0:禁用;1启用]\'',
            'created_at' => 'int(10) NOT NULL DEFAULT \'0\' COMMENT \'创建时间\'',
            'updated_at' => 'int(10) unsigned NULL DEFAULT \'0\' COMMENT \'修改时间\'',
            'PRIMARY KEY (`id`)'
        ], "ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='系统_行为表'");
        
        /* 索引设置 */
        
        
        /* 表数据 */
        $this->insert('{{%sys_action_log}}',['id'=>'26','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'{\"_csrf-backend\":\"9QBxEi9G1PGokoZfrronMmx8pb9O-8DAq7NBuazIja2bSBVNcDWWocarsG3g0WofW0Xjyn6S96Ha0QPWybq9wQ==\",\"LoginForm\":{\"username\":\"admin\",\"password\":\"2589632147\",\"rememberMe\":\"1\"},\"login-button\":\"\"}','ip'=>'2130706433','remark'=>'自动登录','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1530853397','updated_at'=>'1530853397']);
        $this->insert('{{%sys_action_log}}',['id'=>'27','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号密码登录','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1531184930','updated_at'=>'1531184930']);
        $this->insert('{{%sys_action_log}}',['id'=>'28','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'{\"s\":\"\\/site\\/login.html\"}','post_data'=>'[]','ip'=>'1943489871','remark'=>'账号密码登录','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1531190016','updated_at'=>'1531190016']);
        $this->insert('{{%sys_action_log}}',['id'=>'29','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'[]','post_data'=>'{\"_csrf-backend\":\"-eYgD8oWDHUmw3CPRIYpDyvHk_3JEwVjuWKazo8uOKmJlm5euVFfO3a5H9kNq2A6G6zKyvt_RBfTLqOE6llc3g==\",\"config\":{\"wechat_account\":\"\",\"wechat_id\":\"\",\"wechat_rank\":\"4\",\"wechat_appid\":\"wx073786f850de9ffe\",\"wechat_appsecret\":\"f5407a8f95a8c89285f338ec7b347a7a\",\"wechat_token\":\"CFMrt9fjuzNAOJusu9lSgA8JlJbRJnxA\",\"wechat_encodingaeskey\":\"\",\"miniprogram_appid\":\"wx0effa641ca4eb6b3\",\"miniprogram_secret\":\"8816938a3d2f5b33ed7cd5bb09391b2b\",\"wechat_share_title\":\"\",\"wechat_share_details\":\"\",\"wechat_share_url\":\"\"}}','ip'=>'2130706433','remark'=>'修改配置信息','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1531636766','updated_at'=>'1531636766']);
        $this->insert('{{%sys_action_log}}',['id'=>'30','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'{\"s\":\"\\/site\\/login.html\"}','post_data'=>'[]','ip'=>'2104688213','remark'=>'账号密码登录','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1531636778','updated_at'=>'1531636778']);
        $this->insert('{{%sys_action_log}}',['id'=>'31','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"AkEIlul7u0I9bRQD0i76GS_ricuOxT9pS4i6tsmfUCwvO0v3oj_qGHQEW2W1WoBMbprMruahSFgh6c7AsOgxSg==\",\"config\":{\"wechat_account\":\"\",\"wechat_id\":\"\",\"wechat_rank\":\"4\",\"wechat_appid\":\"wx073786f850de9ffe\",\"wechat_appsecret\":\"f5407a8f95a8c89285f338ec7b347a7a\",\"wechat_token\":\"CFMrt9fjuzNAOJusu9lSgA8JlJbRJnxA\",\"wechat_encodingaeskey\":\"\",\"miniprogram_appid\":\"wx0effa641ca4eb6b3\",\"miniprogram_secret\":\"8816938a3d2f5b33ed7cd5bb09391b2b\",\"wechat_share_title\":\"\",\"wechat_share_details\":\"\",\"wechat_share_url\":\"\"}}','ip'=>'2104688213','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1531636798','updated_at'=>'1531636798']);
        $this->insert('{{%sys_action_log}}',['id'=>'32','manager_id'=>'0','behavior'=>'wechat','method'=>'POST','module'=>'app-wechat','controller'=>'api','action'=>'index','url'=>'/wechat/api/index.html','get_data'=>'{\"s\":\"\\/api\\/index.html\",\"signature\":\"9541915406d493f9c1da513442a002688e0de67b\",\"timestamp\":\"1531797468\",\"nonce\":\"102815784\",\"openid\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\"}','post_data'=>'[]','ip'=>'3752255084','remark'=>'{\"errcode\":40001,\"errmsg\":\"invalid credential, access_token is invalid or not latest hint: [0468vr57!]\"}','country'=>'中国','provinces'=>'上海','city'=>'上海','status'=>'1','created_at'=>'1531797469','updated_at'=>'1531797469']);
        $this->insert('{{%sys_action_log}}',['id'=>'33','manager_id'=>'0','behavior'=>'unsubscribe','method'=>'POST','module'=>'app-wechat','controller'=>'api','action'=>'index','url'=>'/wechat/api/index.html','get_data'=>'{\"s\":\"\\/api\\/index.html\",\"signature\":\"9d4bf1526ca80ce1ab6b5f25538a33d687cb38ba\",\"timestamp\":\"1531806385\",\"nonce\":\"72021381\",\"openid\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\"}','post_data'=>'[]','ip'=>'3752255084','remark'=>'调试微信取消关注消息','country'=>'中国','provinces'=>'上海','city'=>'上海','status'=>'1','created_at'=>'1531806385','updated_at'=>'1531806385']);
        $this->insert('{{%sys_action_log}}',['id'=>'34','manager_id'=>'0','behavior'=>'unsubscribe','method'=>'POST','module'=>'app-wechat','controller'=>'api','action'=>'index','url'=>'/wechat/api/index.html','get_data'=>'{\"s\":\"\\/api\\/index.html\",\"signature\":\"81bd2a6d4b9fbd7f37beb875b5d998bf50f8f7ba\",\"timestamp\":\"1531806475\",\"nonce\":\"355771062\",\"openid\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\"}','post_data'=>'[]','ip'=>'3752255084','remark'=>'{\"ToUserName\":\"gh_ee752fe1bd0c\",\"FromUserName\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\",\"CreateTime\":\"1531806475\",\"MsgType\":\"event\",\"Event\":\"unsubscribe\",\"EventKey\":null}','country'=>'中国','provinces'=>'上海','city'=>'上海','status'=>'1','created_at'=>'1531806475','updated_at'=>'1531806475']);
        $this->insert('{{%sys_action_log}}',['id'=>'35','manager_id'=>'0','behavior'=>'unsubscribe','method'=>'POST','module'=>'app-wechat','controller'=>'api','action'=>'index','url'=>'/wechat/api/index.html','get_data'=>'{\"s\":\"\\/api\\/index.html\",\"signature\":\"0f0146485f5ebd0e4165b3a81ffd7bae35680738\",\"timestamp\":\"1531806558\",\"nonce\":\"1328883962\",\"openid\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\"}','post_data'=>'[]','ip'=>'3752255084','remark'=>'{\"ToUserName\":\"gh_ee752fe1bd0c\",\"FromUserName\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\",\"CreateTime\":\"1531806558\",\"MsgType\":\"event\",\"Event\":\"unsubscribe\",\"EventKey\":null}','country'=>'中国','provinces'=>'上海','city'=>'上海','status'=>'1','created_at'=>'1531806559','updated_at'=>'1531806559']);
        $this->insert('{{%sys_action_log}}',['id'=>'36','manager_id'=>'0','behavior'=>'unsubscribe','method'=>'POST','module'=>'app-wechat','controller'=>'api','action'=>'index','url'=>'/wechat/api/index.html','get_data'=>'{\"s\":\"\\/api\\/index.html\",\"signature\":\"259b3563bf1c1df3864ea198fd56ddee1e229042\",\"timestamp\":\"1531806612\",\"nonce\":\"1542754696\",\"openid\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\"}','post_data'=>'[]','ip'=>'3752255084','remark'=>'{\"ToUserName\":\"gh_ee752fe1bd0c\",\"FromUserName\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\",\"CreateTime\":\"1531806612\",\"MsgType\":\"event\",\"Event\":\"unsubscribe\",\"EventKey\":null}','country'=>'中国','provinces'=>'上海','city'=>'上海','status'=>'1','created_at'=>'1531806612','updated_at'=>'1531806612']);
        $this->insert('{{%sys_action_log}}',['id'=>'37','manager_id'=>'0','behavior'=>'unsubscribe','method'=>'POST','module'=>'app-wechat','controller'=>'api','action'=>'index','url'=>'/wechat/api/index.html','get_data'=>'{\"s\":\"\\/api\\/index.html\",\"signature\":\"ffdc984a676d134573c8a7c5a84be338ea365813\",\"timestamp\":\"1531807183\",\"nonce\":\"1278765081\",\"openid\":\"oXtOes8lfAzW4cIhnB4C5ORQZFOs\"}','post_data'=>'[]','ip'=>'3752255084','remark'=>'事件只能包含至多10个字符。','country'=>'中国','provinces'=>'上海','city'=>'上海','status'=>'1','created_at'=>'1531807183','updated_at'=>'1531807183']);
        $this->insert('{{%sys_action_log}}',['id'=>'38','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'[]','post_data'=>'{\"_csrf-backend\":\"3eV72jJd25fFctT24ICpHsUw188mBeBcmfDbGTmiiO2uqyKfZBCu27ARoJ2X2Mtor1a2nGl0sBasm7p4UZfZlQ==\",\"config\":{\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS\"}}','ip'=>'2130706433','remark'=>'修改配置信息','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1532395088','updated_at'=>'1532395088']);
        $this->insert('{{%sys_action_log}}',['id'=>'39','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'[]','post_data'=>'{\"_csrf-backend\":\"w-l2Nd57hT1KEyC7bc-tCC07Ocr7YxbYxifYka-bWpewpy9wiDbwcT9wVNAal89-R11YmbQSRpLzTLnwx64L7w==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS\"}}','ip'=>'2130706433','remark'=>'修改配置信息','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1532396514','updated_at'=>'1532396514']);
        $this->insert('{{%sys_action_log}}',['id'=>'40','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'{\"s\":\"\\/site\\/login.html\"}','post_data'=>'[]','ip'=>'1943489682','remark'=>'账号密码登录','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532396640','updated_at'=>'1532396640']);
        $this->insert('{{%sys_action_log}}',['id'=>'41','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"sn8yxKPXw4euRkPGOfou3mxEjrs0JpJrFkuwPnmXH-uBC0ap-a-25c8kNJV-q3atHx3-iGcf8QxVP-p2D_1pow==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS1\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532397999','updated_at'=>'1532397999']);
        $this->insert('{{%sys_action_log}}',['id'=>'42','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"sn8yxKPXw4euRkPGOfou3mxEjrs0JpJrFkuwPnmXH-uBC0ap-a-25c8kNJV-q3atHx3-iGcf8QxVP-p2D_1pow==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS1\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398036','updated_at'=>'1532398036']);
        $this->insert('{{%sys_action_log}}',['id'=>'43','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"sn8yxKPXw4euRkPGOfou3mxEjrs0JpJrFkuwPnmXH-uBC0ap-a-25c8kNJV-q3atHx3-iGcf8QxVP-p2D_1pow==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398119','updated_at'=>'1532398119']);
        $this->insert('{{%sys_action_log}}',['id'=>'44','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"VzAtn9tdNvwOgqguiWsoKrxlN6JplWnMB_r9i-UAxS1kRFnygSVDnm_g333OOnBZzzxHkTqsCqtEjqfDk2qzZQ==\",\"config\":{\"web_site_title\":\"RageFrame\\u5e94\\u7528\\u5f00\\u53d1\\u5f15\\u64ce\",\"web_site_icp\":\"\",\"web_copyright\":\"\\u00a9 2016 - 2018 RageFrame All Rights Reserved.\",\"web_baidu_push\":\"\",\"web_visit_code\":\"\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398578','updated_at'=>'1532398578']);
        $this->insert('{{%sys_action_log}}',['id'=>'45','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"VzAtn9tdNvwOgqguiWsoKrxlN6JplWnMB_r9i-UAxS1kRFnygSVDnm_g333OOnBZzzxHkTqsCqtEjqfDk2qzZQ==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398586','updated_at'=>'1532398586']);
        $this->insert('{{%sys_action_log}}',['id'=>'46','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'[]','post_data'=>'{\"_csrf-backend\":\"gcgsPUxSeUtXaVygCm-CQnwn_s9N0a2OQQkECoQomLzyhnV4Gh8MByIKKMt9N-A0FkGfnAKg_cR0YmVr7B3JxA==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS1\"}}','ip'=>'2130706433','remark'=>'修改配置信息','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1532398585','updated_at'=>'1532398585']);
        $this->insert('{{%sys_action_log}}',['id'=>'47','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"VzAtn9tdNvwOgqguiWsoKrxlN6JplWnMB_r9i-UAxS1kRFnygSVDnm_g333OOnBZzzxHkTqsCqtEjqfDk2qzZQ==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398723','updated_at'=>'1532398723']);
        $this->insert('{{%sys_action_log}}',['id'=>'48','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"VzAtn9tdNvwOgqguiWsoKrxlN6JplWnMB_r9i-UAxS1kRFnygSVDnm_g333OOnBZzzxHkTqsCqtEjqfDk2qzZQ==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS123\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398744','updated_at'=>'1532398744']);
        $this->insert('{{%sys_action_log}}',['id'=>'49','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"VzAtn9tdNvwOgqguiWsoKrxlN6JplWnMB_r9i-UAxS1kRFnygSVDnm_g333OOnBZzzxHkTqsCqtEjqfDk2qzZQ==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS123\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398761','updated_at'=>'1532398761']);
        $this->insert('{{%sys_action_log}}',['id'=>'50','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"VzAtn9tdNvwOgqguiWsoKrxlN6JplWnMB_r9i-UAxS1kRFnygSVDnm_g333OOnBZzzxHkTqsCqtEjqfDk2qzZQ==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398774','updated_at'=>'1532398774']);
        $this->insert('{{%sys_action_log}}',['id'=>'51','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"VzAtn9tdNvwOgqguiWsoKrxlN6JplWnMB_r9i-UAxS1kRFnygSVDnm_g333OOnBZzzxHkTqsCqtEjqfDk2qzZQ==\",\"config\":{\"webhook_gitee_save_path\":\"\\/www\\/wwwroot\\/map\\/rageframe-advanced\",\"webhook_gitee_git_path\":\"https:\\/\\/gitee.com\\/jianyan94\\/rageframe-advanced\",\"webhook_gitee_password\":\"t2w5HFyRXS1QpWzYBNHer1zgw6shWSMS\"}}','ip'=>'1943489682','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1532398782','updated_at'=>'1532398782']);
        $this->insert('{{%sys_action_log}}',['id'=>'52','manager_id'=>'1','behavior'=>'updateManagerPwd','method'=>'POST','module'=>'sys','controller'=>'manager','action'=>'up-password','url'=>'/backend/sys/manager/up-password.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'修改管理员密码|账号:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534920210','updated_at'=>'1534920210']);
        $this->insert('{{%sys_action_log}}',['id'=>'53','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534920288','updated_at'=>'1534920288']);
        $this->insert('{{%sys_action_log}}',['id'=>'54','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534920294','updated_at'=>'1534920294']);
        $this->insert('{{%sys_action_log}}',['id'=>'55','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534920300','updated_at'=>'1534920300']);
        $this->insert('{{%sys_action_log}}',['id'=>'56','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921021','updated_at'=>'1534921021']);
        $this->insert('{{%sys_action_log}}',['id'=>'57','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921041','updated_at'=>'1534921041']);
        $this->insert('{{%sys_action_log}}',['id'=>'58','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号密码登录','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921100','updated_at'=>'1534921100']);
        $this->insert('{{%sys_action_log}}',['id'=>'59','manager_id'=>'1','behavior'=>'updateManagerPwd','method'=>'POST','module'=>'sys','controller'=>'manager','action'=>'up-password','url'=>'/backend/sys/manager/up-password.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'修改管理员密码|账号:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921265','updated_at'=>'1534921265']);
        $this->insert('{{%sys_action_log}}',['id'=>'60','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921271','updated_at'=>'1534921271']);
        $this->insert('{{%sys_action_log}}',['id'=>'61','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921284','updated_at'=>'1534921284']);
        $this->insert('{{%sys_action_log}}',['id'=>'62','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921290','updated_at'=>'1534921290']);
        $this->insert('{{%sys_action_log}}',['id'=>'63','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921302','updated_at'=>'1534921302']);
        $this->insert('{{%sys_action_log}}',['id'=>'64','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号密码登录','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921311','updated_at'=>'1534921311']);
        $this->insert('{{%sys_action_log}}',['id'=>'65','manager_id'=>'1','behavior'=>'updateManagerPwd','method'=>'POST','module'=>'sys','controller'=>'manager','action'=>'up-password','url'=>'/backend/sys/manager/up-password.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'修改管理员密码|账号:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921331','updated_at'=>'1534921331']);
        $this->insert('{{%sys_action_log}}',['id'=>'66','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号或者密码错误|用户名:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921339','updated_at'=>'1534921339']);
        $this->insert('{{%sys_action_log}}',['id'=>'67','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号密码登录','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921373','updated_at'=>'1534921373']);
        $this->insert('{{%sys_action_log}}',['id'=>'68','manager_id'=>'1','behavior'=>'updateManagerPwd','method'=>'POST','module'=>'sys','controller'=>'manager','action'=>'up-password','url'=>'/backend/sys/manager/up-password.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'修改管理员密码|账号:admin','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921413','updated_at'=>'1534921413']);
        $this->insert('{{%sys_action_log}}',['id'=>'69','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'[]','post_data'=>'[]','ip'=>'2130706433','remark'=>'账号密码登录','country'=>'本机地址','provinces'=>'本机地址','city'=>'','status'=>'1','created_at'=>'1534921419','updated_at'=>'1534921419']);
        $this->insert('{{%sys_action_log}}',['id'=>'70','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'{\"s\":\"\\/site\\/login.html\"}','post_data'=>'[]','ip'=>'1943489993','remark'=>'账号或者密码错误|用户名:admin','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1536050387','updated_at'=>'1536050387']);
        $this->insert('{{%sys_action_log}}',['id'=>'71','manager_id'=>'0','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'{\"s\":\"\\/site\\/login.html\"}','post_data'=>'[]','ip'=>'1943489993','remark'=>'账号或者密码错误|用户名:admin','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1536050393','updated_at'=>'1536050393']);
        $this->insert('{{%sys_action_log}}',['id'=>'72','manager_id'=>'1','behavior'=>'login','method'=>'POST','module'=>'app-backend','controller'=>'site','action'=>'login','url'=>'/backend/site/login.html','get_data'=>'{\"s\":\"\\/site\\/login.html\"}','post_data'=>'[]','ip'=>'1943489993','remark'=>'账号密码登录','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1536050398','updated_at'=>'1536050398']);
        $this->insert('{{%sys_action_log}}',['id'=>'73','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"ODDUcDx2oBm2y0SpA5YzrBfJMe88g3bIbasfxDnFdXV2dosKW07rXsG7Ddlp73LAU4BJrHnFOoco3mvxXIQTKg==\",\"config\":{\"wechat_account\":\"\",\"wechat_id\":\"wx073786f850de9ffe\",\"wechat_rank\":\"4\",\"wechat_appid\":\"wx6e1bea018ad2fe57\",\"wechat_appsecret\":\"f5407a8f95a8c89285f338ec7b347a7a\",\"wechat_token\":\"CFMrt9fjuzNAOJusu9lSgA8JlJbRJnxA\",\"wechat_encodingaeskey\":\"\",\"miniprogram_appid\":\"wx0effa641ca4eb6b3\",\"miniprogram_secret\":\"8816938a3d2f5b33ed7cd5bb09391b2b\",\"wechat_share_title\":\"\",\"wechat_share_details\":\"\",\"wechat_share_url\":\"\"}}','ip'=>'1943489993','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1536050458','updated_at'=>'1536050458']);
        $this->insert('{{%sys_action_log}}',['id'=>'74','manager_id'=>'1','behavior'=>'updateConfig','method'=>'POST','module'=>'sys','controller'=>'config','action'=>'update-info','url'=>'/backend/sys/config/update-info.html','get_data'=>'{\"s\":\"\\/sys\\/config\\/update-info.html\"}','post_data'=>'{\"_csrf-backend\":\"ODDUcDx2oBm2y0SpA5YzrBfJMe88g3bIbasfxDnFdXV2dosKW07rXsG7Ddlp73LAU4BJrHnFOoco3mvxXIQTKg==\",\"config\":{\"wechat_account\":\"\",\"wechat_id\":\"\",\"wechat_rank\":\"4\",\"wechat_appid\":\"wx073786f850de9ffe\",\"wechat_appsecret\":\"f5407a8f95a8c89285f338ec7b347a7a\",\"wechat_token\":\"CFMrt9fjuzNAOJusu9lSgA8JlJbRJnxA\",\"wechat_encodingaeskey\":\"\",\"miniprogram_appid\":\"wx0effa641ca4eb6b3\",\"miniprogram_secret\":\"8816938a3d2f5b33ed7cd5bb09391b2b\",\"wechat_share_title\":\"\",\"wechat_share_details\":\"\",\"wechat_share_url\":\"\"}}','ip'=>'1943489993','remark'=>'修改配置信息','country'=>'中国','provinces'=>'浙江','city'=>'宁波','status'=>'1','created_at'=>'1536050693','updated_at'=>'1536050693']);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%sys_action_log}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

